# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kaira Villanueva
email: ffv2102@columbia.edu
description: Developer and Ecologist
baseurl: "http://kairaygun.github.io"
localhost: 4000
mainhost: "http://localhost:4000"
url: kaira.one
twitter_username: kairavillanueva
github_username: kairavillanueva
currently_reading: The Manga Guide to Regression Analysis
excerpt_separator: <!--more-->

# Plugins
whitelist: []
gems:      [jekyll-paginate]

paginate: 2
destination: _site/blog
paginate_path: "blog/page:num"



# Build settings
markdown: kramdown
