title: Kaira Villanueva
email: fzf.villanueva@gmail.com
description: Kaira Villanueva Portfolio - UX Engineer
baseurl: ""
localhost: 4000
mainhost: "http://localhost:4000"
url: kaira.design

# Build settings
markdown: kramdown
defaults:
  - scope:
      path: "assets/images/projects/"
    values:
      image: true
sass:
    sass_dir: _sass
plugins:
  - jekyll-feed
permalink: /:categories/:year/:month/:day/:title:output_ext
